### Create user
POST {{protocol}}{{host}}:{{port}}/users
Content-Type: application/json
Accept: application/json

{
  "username": "user3211",
  "password": "passwordd",
  "isAdmin": false
}

> {%
    client.test(
        "Request executed successfully",
        function() {
            client.assert(response.status === 201, "Response status is not 201");
        }
    )

    client.test(
        "Response body contains a token",
        function() {
            client.assert(response.body.token !== undefined, "Token not found in response body");
        }
    );
%}

### Create user with invalid username
POST {{protocol}}{{host}}:{{port}}/users
Content-Type: application/json
Accept: application/json

{
  "username": "u",
  "password": "password",
  "isAdmin": false
}

> {%
    client.test(
        "Request failed",
        function() {
            client.assert(response.status === 400, "Response status is not 400");
        }
    )
%}

### Create user with invalid password
POST {{protocol}}{{host}}:{{port}}/users
Content-Type: application/json
Accept: application/json

{
  "username": "user123",
  "password": "pass",
  "isAdmin": false
}

> {%
    client.test(
        "Request failed",
        function() {
            client.assert(response.status === 400, "Response status is not 400");
        }
    )
%}

### Create user with existing username
POST {{protocol}}{{host}}:{{port}}/users
Content-Type: application/json
Accept: application/json

{
  "username": "user123",
  "password": "password",
  "isAdmin": false
}

> {%
    client.test(
        "Request failed",
        function() {
            client.assert(response.status === 400, "Response status is not 400");
        }
    )
%}